#!/bin/bash

hc() {
    herbstclient "$@"
}

#==============================================================================
# startup 
#==============================================================================

hc emit_hook reload

# load theme settings
source ~/src/herbstluft/theme.sh 

#-external---------------------------------------------------------------------
# set wallpaper
feh --bg-scale ~/mm/image/wp/IRC-o-meter.png &#haskell-ornament.jpg
# start compositor
compton -f --inactive-dim 0.1 -O 0.05 -I 0.95 -b
# turn off screensaver
xset s noblank

# unlock, just to be sure
hc unlock

# monitor setup 
hc detect_monitors

#-panel------------------------------------------------------------------------
# kill previously running panels
killall dzen2 &

panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

#==============================================================================
# settings
#==============================================================================
hc set always_show_frame 0
hc set auto_detect_monitors 1
 set default_direction_external_only 0
hc set default_frame_layout 3 # grid
hc set focus_follows_mouse 1
hc set focus_stealing_prevention 1
hc set frame_active_opacity 100
hc set frame_bg_transparent 0
hc set frame_normal_opacity 100
hc set gapless_grid 0
hc set mouse_recenter_gap 1
hc set pseudotile_center_threshold 0
hc set raise_on_click 1
hc set raise_on_focus 0
hc set raise_on_focus_temporarily 1
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 0
hc set snap_distance 20
hc set snap_gap 10
hc set swap_monitors_to_get_tag 0
hc set tree_style '╾│ ├└╼─┐'
hc set wmname 'Herbstluftwm'

#-rules------------------------------------------------------------------------
hc unrule -F
hc rule focus=on # normally focus new clients

# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class~'(qiv)' pseudotile=on
hc rule class~'([Ff]irefox|Vimperator)' tag=1
hc rule class='gimp' tag='gimp'
hc rule class='vlc' pseudotile=on
hc rule class='mplayer' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule instance~'(.*X11-XDialogPeer.*)' pseudotile=on

#==============================================================================
# keybindings
#==============================================================================
# remove all existing keybindings
hc keyunbind --all

# set  mod key
Mod=Mod4   # Use the super key as the main modifier

# general
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn lilyterm 

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# resizing gap
hc keybind $Mod-g               cycle_value frame_gap 0 10 20 30 40 50 60 80
hc keybind $Mod-Shift-g         cycle_value frame_gap 80 60 50 40 30 20 10 0 

# resizing frames
resizestep=0.005
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-space           cycle_layout 1
hc keybind $Mod-r               remove
hc keybind $Mod-s               split vertical 0.5
hc keybind $Mod-Shift-s         split horizontal 0.5
hc keybind $Mod-f               fullscreen toggle
hc keybind $Mod-Shift-f         floating toggle
hc keybind $Mod-p               pseudotile toggle
hc keybind $Mod-u               split bottom 0.5
hc keybind $Mod-o               split right 0.5

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
#hc keybind $Mod-BackSpace   cycle_monitor      # find different key
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# media keys
hc keybind XF86AudioNext spawn mpc --host passwd@localhost next
hc keybind XF86AudioPrev spawn mpc --host passwd@localhost prev
hc keybind XF86AudioPlay spawn mpc --host passwd@localhost toggle
hc keybind XF86AudioStop spawn mpc --host passwd@localhost stop

hc keybind XF86AudioRaiseVolume spawn amixer sset Master 1%+
hc keybind XF86AudioLowerVolume spawn amixer sset Master 5%-
hc keybind XF86AudioMute spawn amixer sset Master toggle

hc keybind XF86AudioMedia spawn urxvt -e ncmpcpp
hc keybind XF86Tools spawn gnome-terminal -e ncmpcpp
hc keybind XF86Mail spawn urxvt -e sup 

# turn DPMS on/off
hc keybind $Mod-x spawn xset +dpms
hc keybind $Mod-Shift-x spawn xset -dpms

# screen lock
hc keybind $Mod-Escape spawn slock

# screenshot
hc keybind Print spawn scrot

# dmenu
hc keybind $Mod-BackSpace spawn dmenu_run -fn 'snap-7' -nb '#151515' -nf '#919191' -sb '#151515' -sf '#c98f0a'

#-tags-------------------------------------------------------------------------
tag_names=( {1..9} 0 )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# GIMP
# ensure there is a gimp tag
hc add gimp
hc load gimp '
(split horizontal:0.850000:0
(split horizontal:0.200000:1
(clients vertical:0)
(clients grid:0))
(clients vertical:0))
' # load predefined layout
# center all other gimp windows on gimp tag
hc rule class=Gimp tag=gimp index=01 pseudotile=on
hc rule class=Gimp windowrole~'gimp-(image-window|toolbox|dock)' \
        pseudotile=off
hc rule class=Gimp windowrole=gimp-toolbox focus=off index=00
hc rule class=Gimp windowrole=gimp-dock focus=off index=1

#hc keybind $Mod-g use gimp
#hc keybind $Mod-Shift-g move gimp

#for tag in ${TAG_NAMES}; do
#	layoutfile=${XDG_DATA_HOME}/herbstluftwm/layout/${tag}
#	if [ -f ${layoutfile} ]; then
#		hc load ${tag} $(cat ${layoutfile})
#	fi
#done
